<a href="https://colab.research.google.com/github/kirant16/kirant16/blob/main/Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
RA = int(input("Enter the number of rows for Matrix A:"))
CA = int(input("Enter the number of columns for Matrix A:"))
print("Enter Matrix A row wise and hit enter after every element input ")
A = [[int(input()) for x in range (CA)] for y in range(RA)]
print("Matrix A:")
print(A)
RB = int(input("Enter the number of rows for Matrix B:"))
CB = int(input("Enter the number of columns for Matrix B:"))
print("Enter Matrix B row wise and hit enter after every element input")
B = [[int(input()) for x in range (CB)] for y in range(RB)]
print("Matrix B:")
print(B)

Enter the number of rows for Matrix A:3
Enter the number of columns for Matrix A:3
Enter Matrix A row wise and hit enter after every element input 
1
3
4
2
5
7
5
9
6
Matrix A:
[[1, 3, 4], [2, 5, 7], [5, 9, 6]]
Enter the number of rows for Matrix B:3
Enter the number of columns for Matrix B:3
Enter Matrix B row wise and hit enter after every element input
1
0
0
0
1
0
0
0
1
Matrix B:
[[1, 0, 0], [0, 1, 0], [0, 0, 1]]


In [ ]:
def matrix_mul(A, B,result):
    # write your code
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
 
    for r in result:
        print(r)
    return r

In [ ]:
if CA==RB:
    result = []
    for i in range(RA):        
        z =[]
        for j in range(CB):     
             z.append(0)
        result.append(z)

    print("Matrix A *B Results :")
    matrix_mul(A, B,result)
    
else:
    print("Matrix multiplication not possible")

Matrix A *B Results :
[1, 3, 4]
[2, 5, 7]
[5, 9, 6]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
list_idx = int(input("Enter the number of elements for list:"))
lst =[]
for i in range(list_idx):
   lst.append(float(input()))

print(lst)

Enter the number of elements for list:5
2.0
6.0
1.2
5.8
20.0
[2.0, 6.0, 1.2, 5.8, 20.0]


In [ ]:
sum_val =0
for i in range(len(lst)):
  sum_val += lst[i]
  #print(sum_val)

lst_dash=[]
cum_sum = [0]
for i in range(len(lst)):
  lst_dash.append(lst[i]/sum_val)
  #cum_sum.append(0)
#print(lst_dash)
#print(cum_sum)

for i in range(len(lst)):
  cum_sum.append(cum_sum[i]+lst_dash[i])
  #print(cum_sum)
del cum_sum[0]
#print(cum_sum)

In [ ]:
from random import uniform
import numpy as np

r = np.random.uniform(0,1)
r

0.3133873291854964

In [ ]:
final_val =0
for i in range(len(cum_sum)):
  if r <= cum_sum[i]:
    final_val = lst[i]
    break
    
print(final_val)

5.8


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
String = str(input("Enter the string input:"))

Enter the string input:1@%$&DFGKSKJ


In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(input_string):
    # write your code
    x = re.sub("[0-9]","#", input_string)
    y = re.findall("#", x)
    final_str = ''.join(y)
    return(final_str) # modified string which is after replacing the # with digits

result_str = replace_digits(String)
print(result_str)

#


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
import copy

In [ ]:
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

In [ ]:
list_num = int(input("Enter the number of total Students:"))
#CA = int(input("Enter the number of columns for Matrix A:"))
print("Enter Student Name and hit enter after every element input ")
Students = [str(input()) for x in range (list_num)]
print("Enter Student Marks and hit enter after every element input ")
Marks = [int(input()) for x in range (list_num)]
print(Students)
print(Marks)

Enter the number of total Students:4
Enter Student Name and hit enter after every element input 
Std1
Std2
Std3
Std4
Enter Student Marks and hit enter after every element input 
98
78
65
54
['Std1', 'Std2', 'Std3', 'Std4']
[98, 78, 65, 54]


In [ ]:
def top_5_list(Marks_desc1,Marks_original):
  Marks_desc1.sort(reverse=True)
  Marks_desc = Marks_desc1
  top_5= Marks_desc[0:5]
  print(Marks_desc)
  print("Top 5 Students:")
  for i in range(len(top_5)):
    for j in range(len(Marks_original)):
      if top_5[i] == Marks_original[j]:
        #print("Top 5 Students:")
        print(str(Students[j])+" "+ str(Marks_original[j]))

  return 0


In [ ]:
def least_5_list(Marks_asc1,Marks_original):
  Marks_asc1.sort(reverse=False)
  Marks_asc = Marks_asc1
  #print(Marks_asc)
  least_5= Marks_asc[0:5]
 # print(least_5)
  print("Least 5 Students:")
  for i in range(len(least_5)):
    for j in range(len(Marks_original)):
      if least_5[i] == Marks_original[j]:
        print(str(Students[j])+" "+ str(Marks_original[j]))
  return Marks_asc

In [ ]:
def interquartile_list(Marks_asc,Marks_original):
  start_p = 25/100
  end_p = 75/100
  Start_pos = round(len(Marks_asc)*start_p)
  End_pos = round(len(Marks_asc)*end_p)
  print(" All Data Points between 25th and 75th Percentile")
  Interquartile_range = Marks_asc[Start_pos:End_pos]
  #print(Interquartile_range)
  for i in range(len(Interquartile_range)-1):
    for j in range(len(Marks_original)):
      if Interquartile_range[i] == Marks_original[j]:
        print(str(Students[j])+" "+ str(Marks_original[j]))
  return 0

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
  Marks_original = copy.deepcopy(Marks)
  Marks_asc1 = copy.deepcopy(Marks)
  Marks_desc1 = copy.deepcopy(Marks)
  type(Marks_original)
    # write code for computing top top 5 students
  top_5_students = top_5_list(Marks_desc1,Marks_original)
  # write code for computing top least 5 students
  least_5_students = least_5_list(Marks_asc1,Marks_original)
  # write code for computing top least 5 students
  students_within_25_and_75 = interquartile_list(least_5_students,Marks_original)
    
  return top_5_students, least_5_students, students_within_25_and_75

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)
#print(# those values)

[98, 78, 65, 54]
Top 5 Students:
Std1 98
Std2 78
Std3 65
Std4 54
Least 5 Students:
Std4 54
Std3 65
Std2 78
Std1 98
 All Data Points between 25th and 75th Percentile
Std3 65


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    distance_val =[]
    closest_points_to_p=[]
    for i in S:
      X2 = i[0]**2
      y2 = i[1]**2
      p2= P[0]**2
      q2= P[1]**2
      Numerator = (i[0]*P[0])+(i[1]*P[1])
      Dr1 = math.sqrt(X2+y2)
      Dr2 = math.sqrt(p2+q2)
      Denominator = Dr1*Dr2
      final_val = Numerator/Denominator
      cosine_distance = math.acos(final_val)
      distance_val.append((cosine_distance, i))
      #print(cosine_distance)
    for item in sorted(distance_val, key=lambda x: x[0])[:5]:
        closest_points_to_p.append(item[1])
    # write your code here
    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print("Five Closest point:", *[point for point in points], sep="\n")

#print() #print the returned values

Five Closest point:
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [32]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,i):
    # your code
    Red_point_val = -1 
   
    k = i
    k = k.replace('x', '*%s' % Red[0][0])
    k = k.replace('y', '*%s' % Red[0][1])
    if eval(k)>0:
      Red_point_val = 1

    Blue_point_val = -1 * Red_point_val
    
    for idx in red:
      r= i
      r = r.replace('x', '*%s' % idx[0])
      r = r.replace('y', '*%s' % idx[1])
      if Red_point_val == 1 and eval(r)<0:
        return "No"
      if Red_point_val == -1 and eval(r) >0:
        return "No"
    
    for idx in blue:
      b = i
      b = b.replace('x', '*%s' % idx[0])
      b = b.replace('y', '*%s' % idx[1])
      if Blue_point_val == 1 and eval(b)<0:
        return "No"
      if Blue_point_val == -1 and eval(b) >0:
        return "No"

    return "Yes"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [149]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#run your code in the function for each of the inputs mentioned above and make sure that you get the same results

# you can free to change all these codes/structure
import re
def curve_smoothing(string):
    # your code
    x = re.sub("_", "0", S)
    lx = re.split(",", x)
    lst_S =[]
    idx =[]
    for i in lx:
      lst_S.append(int(i))
      if int(i)>0:
        idx.append(lst_S.index(int(i)))
    final_lst = []
    val = lst_S[idx[0]]
    k = (idx[0]+1)
    val1 = val/k
    for i in range(k):
      final_lst.append(int(val1))
    
    if len(idx)>1:
      del final_lst[-1]
      for x in range(len(idx)-1):
        x = x+1
        c = idx[x]
        val2 = final_lst[0]+lst_S[c]
        #print(val2)
        for y in range(len(idx)-1):
          val3 = idx[y]
          y = y+1
          val4 = idx[y]
          len_val = val4 -val3 +1

        #val3 = (idx[x]+1)-idx[x]+1
        fial_val2 = val2/len_val
        
      for i in range(len_val):
        final_lst.append(int(fial_val2))
    if len(idx)< len(lst_S):
      del final_lst[-1]
      last = final_lst[-1]
      #print(last)
      len_last = len(lst_S) - idx[-1]
      right_val = last/len_last
      for i in range(len_last):
        final_lst.append(int(right_val))
      #print(final_lst) 
    return final_lst

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [22]:
# Referred to stack overflow
A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]

d1 = {
'F1S1': 0,
'F2S1': 0,
'F3S1': 0,
'F4S1': 0,
'F5S1': 0,
'F1S2': 0,
'F2S2': 0,
'F3S2': 0,
'F4S2': 0,
'F5S2': 0,
'F1S3': 0,
'F2S3': 0,
'F3S3': 0,
'F4S3': 0,
'F5S3': 0,
}

d2 = {
'S1': 0,
'S2': 0,
'S3': 0
}


def compute_conditional_probabilites(A):
    for i in range(len(A)):
       k = A[i][0] + A[i][1]
       d1[k] += 1
       d2[A[i][1]] += 1

compute_conditional_probabilites(A)

print('a.P(F=F1|S==S1)', (d1['F1S1']/d2['S1']), ', P(F=F1|S==S2)',(d1['F1S2']/d2['S2']),', P(F=F1|S==S3)',(d1['F1S3']/d2['S3']))
print('b.P(F=F2|S==S1)', (d1['F2S1']/d2['S1']), ', P(F=F2|S==S2)',(d1['F2S2']/d2['S2']),', P(F=F2|S==S3)',(d1['F2S3']/d2['S3']))
print('c.P(F=F3|S==S1)', (d1['F3S1']/d2['S1']), ', P(F=F3|S==S2)',(d1['F3S2']/d2['S2']),', P(F=F3|S==S3)',(d1['F3S3']/d2['S3']))
print('d.P(F=F4|S==S1)', (d1['F4S1']/d2['S1']), ', P(F=F4|S==S2)',(d1['F4S2']/d2['S2']),', P(F=F4|S==S3)',(d1['F4S3']/d2['S3']))
print('e.P(F=F5|S==S1)', (d1['F5S1']/d2['S1']), ', P(F=F5|S==S2)',(d1['F5S2']/d2['S2']),', P(F=F5|S==S3)',(d1['F5S3']/d2['S3']))



a.P(F=F1|S==S1) 0.25 , P(F=F1|S==S2) 0.3333333333333333 , P(F=F1|S==S3) 0.0
b.P(F=F2|S==S1) 0.25 , P(F=F2|S==S2) 0.3333333333333333 , P(F=F2|S==S3) 0.3333333333333333
c.P(F=F3|S==S1) 0.0 , P(F=F3|S==S2) 0.3333333333333333 , P(F=F3|S==S3) 0.3333333333333333
d.P(F=F4|S==S1) 0.25 , P(F=F4|S==S2) 0.0 , P(F=F4|S==S3) 0.3333333333333333
e.P(F=F5|S==S1) 0.25 , P(F=F5|S==S2) 0.0 , P(F=F5|S==S3) 0.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [39]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    S3 = S1.split()
    S4 = S2.split()
    same =[]
    Diff_S4=[]
    for i in range(len(S3)):
      for j in range(len(S4)):
        if S3[i] == S4[j]:
          same.append(S4[j])
    a = len(same)
    list_difference = []
    for item in S3:
      if item not in S4:
        list_difference.append(item)

    b = list_difference
    list_difference_S4 = []
    for item in S4:
      if item not in S3:
        list_difference_S4.append(item)

    c = list_difference_S4
    # your code
    return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [6]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

import math as m
# you can free to change all these codes/structure
def compute_log_loss(A):
    res = 0
    for idx in A:
      a= 0
      b = 0
      a = idx[0] * m.log10(idx[1])
      b = (1- idx[0])*m.log10(1-idx[1])
      res = a+b+res
    len_log = len(A)
    loss = (-1)*res/len_log
    #print(final_log_val)
    # your code
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
